import Carousel from "@/components/Carousel";
import Loader from "@/components/Loader";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 3000);
  }, []);

  return (
    <>
      <Head>
        <title>zirkelstudio. | interior photography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen grid place-items-center relative">
        {loading && <Loader />}
        <Carousel />
      </main>
    </>
  );
}
